FROM duluca/minimal-node-build-env:8.9.4 as builder

# project variables

ENV SRC_DIR /usr/src
ENV GIT_REPO https://github.com/
ENV SRC_CODE_LOCATION .
ENV BUILD_SCRIPT build:prod

# get source code

RUN mkdir -p $SRC_DIR
WORKDIR $SRC_DIR

# if necessary, do SSH setup here or copy source code from local or
CI environment

RUN git clone $GIT_REPO .

# COPY $SRC_CODE_LOCATION .

RUN npm install
RUN npm run $BUILD_SCRIPT
